package main

import (
	"bytes"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"
	"time"
)

func main() {
	// 1. READ THE SHARED SECRET FILE
	// This file is generated by ZITADEL in the mounted 'secrets' folder
	tokenPath := "./secrets/admin.pat"
	
	fmt.Println("Waiting for token file...")
	var tokenBytes []byte
	var err error

	// Simple retry loop to wait for Docker/ZITADEL to finish writing the file
	for i := 0; i < 20; i++ {
		tokenBytes, err = os.ReadFile(tokenPath)
		// Check for error and ensure the file is not empty
		if err == nil && len(strings.TrimSpace(string(tokenBytes))) > 0 {
			break
		}
		time.Sleep(2 * time.Second)
		fmt.Print(".")
	}
	fmt.Println()

	if err != nil {
		fmt.Println("Error reading token file. Is ZITADEL fully started and the 'secrets' volume mounted correctly?")
		os.Exit(1)
	}

	token := strings.TrimSpace(string(tokenBytes))
	fmt.Println("Token found successfully!")

	// 2. PREPARE REQUEST (Hardcoded values)
	orgName := "Go-Auto-Org-" + time.Now().Format("150405") // Use timestamp to ensure uniqueness
	url := "http://localhost:8080/management/v1/orgs"
	jsonBody := []byte(fmt.Sprintf(`{"name": "%s"}`, orgName))

	req, err := http.NewRequest("POST", url, bytes.NewBuffer(jsonBody))
	if err != nil {
		panic(err)
	}
	req.Header.Set("Authorization", "Bearer "+token)
	req.Header.Set("Content-Type", "application/json")

	// 3. EXECUTE
	client := &http.Client{Timeout: 10 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		panic(err)
	}
	defer resp.Body.Close()

	// 4. RESULT
	body, _ := io.ReadAll(resp.Body)
	fmt.Println("----------------------------------------")
	fmt.Println("Status:", resp.Status)
	fmt.Println("Response:", string(body))
	fmt.Println("----------------------------------------")
}