#!/bin/bash
set -e

ZITADEL_API_URL="http://localhost:8080"

echo "--- Starting ZITADEL Custom Provisioning (API Mode) ---"

# 1. Wait for the PAT file (generated by ZITADEL startup)
echo "Waiting for Admin PAT file..."
while [ ! -f "$ZITADEL_PAT_KEY_PATH" ]; do
    sleep 2
done
echo "PAT Found: $ZITADEL_PAT_KEY_PATH"

# Read the PAT token from the file
PAT_TOKEN=$(cat "$ZITADEL_PAT_KEY_PATH")

if [ -z "$PAT_TOKEN" ]; then
    echo "Error: PAT file is empty!"
    exit 1
fi

# 2. Helper function to make API calls
function call_api() {
    local method=$1
    local endpoint=$2
    local data=$3

    curl -s -X "$method" \
        "${ZITADEL_API_URL}${endpoint}" \
        -H "Authorization: Bearer ${PAT_TOKEN}" \
        -H "Content-Type: application/json" \
        -d "$data"
}

# 3. Create the Organization
ORG_NAME="Kowiste Services"
echo "Attempting to create Organization: $ORG_NAME"

# ZITADEL Management API: POST /v1/orgs
RESPONSE=$(call_api "POST" "/management/v1/orgs" "{\"name\": \"$ORG_NAME\"}")

# Check if creation was successful or if it already exists
if echo "$RESPONSE" | grep -q "\"id\""; then
    ORG_ID=$(echo "$RESPONSE" | jq -r '.id')
    echo "SUCCESS: Organization '$ORG_NAME' created with ID: $ORG_ID"
elif echo "$RESPONSE" | grep -q "already exists"; then
    echo "INFO: Organization '$ORG_NAME' already exists."
else
    echo "WARNING: Unexpected response from ZITADEL API:"
    echo "$RESPONSE"
fi

echo "--- Custom provisioning finished. ---"